# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Anthony Del Rosario
author: Anthony Del Rosario
email: adelrosarioh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Anthony Del Rosario, a Senior Software Engineer from Dominican Republic with 8+ years of professional experience 
  building awesome software applications for health care, government, telecommunications and banking industries. 

  Here I share my thoughts on Software, Programming, Tools and more.
url: 'http://adelrosarioh.me/'

# Config for contrast
permalink: /:title/
lang: 'en'
excerpt_separator: "\n\n\n"
date_format: '%B %d, %Y'

# Layout

sidebar: true # show a sidebar instead of the usual header
show_excerpts: true # show article excerpts on the home page
show_related: true # show the previous and next links after every post
show_description: false # show the site description in the sidebar
show_title: false # always keep the site title visible

# Styling

dark_header: false # always keep the header dark
minimal: true # use simpler style

# Menu

navigation:
  - { title: Thoughts, file: 'index.html' }
  - { title: About, file: 'about.html' }

external: # see http://fontawesome.com/icons
  - { title: Mail, icon: envelope, url: 'mailto:adelrosarioh@gmail.com' }
  - { title: Github, icon: github, url: 'https://github.com/adelrosarioh' }
  - { title: Subscribe, icon: rss, url: '/feed.xml' }

plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
