baseURL: https://adelrosarioh.me/
languageCode: en-us
title: Anthony Del Rosario - Software Engineer
module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: development # to enable google analytics, opengraph, twitter-cards and schema.
  title: Anthony Del Rosario
  description: "Welcome to my personal website!"
  keywords:
    [
      Blog,
      Portfolio,
      Website,
      Software,
      Developer,
      Dominican,
      BackEnd,
      FrontEnd,
      .NET,
      React,
      Angular,
      Web,
    ]
  author: Me
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Anthony Del Rosario
    subtitle: "Hi! I'm a Software Engineer from Dominican Republic"
    # imageUrl: ""
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: my image
    # buttons:
    # - name: Posts
    # url: posts
    # - name: Tags
    # url: tags

  # home-info mode
  # homeInfoParams:
  # Title: "Hi there \U0001F44B"
  # Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/adelrosarioh"
    - name: github
      url: "https://github.com/adelrosarioh"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: more
      name: More about me
      url: /about-me/
      weight: 10
    - identifier: more
      name: More about me
      url: /about-me/
      weight: 10
    - identifier: resume
      name: My Resume
      url: https://mellow-cheesecake-2e6299.netlify.app/
      weight: 20
    - identifier: projects
      name: My projects
      url: /projects/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
